# Generated by Django 4.2.7 on 2026-02-06 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(db_index=True, help_text='Name of the dataset (typically filename without extension)', max_length=255)),
                ('file', models.FileField(help_text='CSV file containing equipment data', upload_to='datasets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when dataset was uploaded')),
                ('total_equipment_count', models.IntegerField(default=0, help_text='Total number of equipment records in this dataset', validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_flowrate', models.FloatField(default=0.0, help_text='Average flowrate across all equipment in dataset', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('avg_pressure', models.FloatField(default=0.0, help_text='Average pressure across all equipment in dataset', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('avg_temperature', models.FloatField(default=0.0, help_text='Average temperature across all equipment in dataset')),
                ('type_distribution', models.JSONField(blank=True, default=dict, help_text='Dictionary mapping equipment types to their counts')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status - False indicates archived dataset')),
                ('user', models.ForeignKey(help_text='User who uploaded this dataset', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset History',
                'verbose_name_plural': 'Dataset Histories',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at', 'user'], name='equipment_d_uploade_843810_idx'), models.Index(fields=['is_active', 'user'], name='equipment_d_is_acti_9ff695_idx')],
            },
        ),
    ]
